// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

export class ClickHouseInstallation extends pulumi.CustomResource {
    /**
     * Get an existing ClickHouseInstallation resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): ClickHouseInstallation {
        return new ClickHouseInstallation(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:clickhouse.altinity.com/v1:ClickHouseInstallation';

    /**
     * Returns true if the given object is an instance of ClickHouseInstallation.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ClickHouseInstallation {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ClickHouseInstallation.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"clickhouse.altinity.com/v1">;
    public readonly kind!: pulumi.Output<"ClickHouseInstallation">;
    public readonly metadata!: pulumi.Output<ObjectMeta>;
    public readonly spec!: pulumi.Output<{[key: string]: any}>;

    /**
     * Create a ClickHouseInstallation resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ClickHouseInstallationArgs, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (!(opts && opts.id)) {
            inputs["apiVersion"] = "clickhouse.altinity.com/v1";
            inputs["kind"] = "ClickHouseInstallation";
            inputs["metadata"] = args ? args.metadata : undefined;
            inputs["spec"] = args ? args.spec : undefined;
        } else {
            inputs["apiVersion"] = undefined /*out*/;
            inputs["kind"] = undefined /*out*/;
            inputs["metadata"] = undefined /*out*/;
            inputs["spec"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(ClickHouseInstallation.__pulumiType, name, inputs, opts);
    }
}

/**
 * The set of arguments for constructing a ClickHouseInstallation resource.
 */
export interface ClickHouseInstallationArgs {
    readonly apiVersion?: pulumi.Input<"clickhouse.altinity.com/v1">;
    readonly kind?: pulumi.Input<"ClickHouseInstallation">;
    readonly metadata?: pulumi.Input<ObjectMeta>;
    readonly spec?: pulumi.Input<{[key: string]: any}>;
}
